# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
